FROM docker.io/golang:1.22-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev \
    gcc pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
